const tracks = [
 {id:1,title:"Golden Hour",artist:"Luna Sol",album:"Soft Focus",genre:"Chill",duration:"3:24",src:"https://cdn.pixabay.com/download/audio/2022/10/25/audio_946b2f0b25.mp3?filename=lofi-study-112191.mp3",art:"https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=500&q=85"},
 {id:2,title:"Midnight City Lights",artist:"Nova Bloom",album:"After Hours",genre:"Electronic",duration:"3:41",src:"https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=chill-ambient-11355.mp3",art:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=500&q=85"},
 {id:3,title:"Palmwine Dreams",artist:"Kofi Waves",album:"Afro Vibes Vol. 1",genre:"Afrobeats",duration:"2:58",src:"https://cdn.pixabay.com/download/audio/2022/08/02/audio_884fe92c21.mp3?filename=summer-walk-152722.mp3",art:"https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=500&q=85"},
 {id:4,title:"Cloud Nine",artist:"Mira June",album:"Little Joys",genre:"Pop",duration:"3:12",src:"https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=good-night-160166.mp3",art:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=500&q=85"},
 {id:5,title:"Slow Motion",artist:"The Daydreams",album:"Blue Room",genre:"R&B",duration:"4:02",src:"https://cdn.pixabay.com/download/audio/2022/02/22/audio_d1718ab41b.mp3?filename=relaxing-145038.mp3",art:"https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=500&q=85"},
 {id:6,title:"Better Days Ahead",artist:"Juno Grey",album:"New Light",genre:"Chill",duration:"3:36",src:"https://cdn.pixabay.com/download/audio/2022/10/30/audio_946a4a7d3a.mp3?filename=lofi-vibes-124008.mp3",art:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=500&q=85"},
 {id:7,title:"Electric Heart",artist:"Nova Bloom",album:"Neon Garden",genre:"Electronic",duration:"3:18",src:"https://cdn.pixabay.com/download/audio/2022/11/22/audio_2c1c1a1f9a.mp3?filename=electronic-future-beats-117997.mp3",art:"https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=500&q=85"},
 {id:8,title:"Sunrise in Lagos",artist:"Kofi Waves",album:"Homecoming",genre:"Afrobeats",duration:"3:09",src:"https://cdn.pixabay.com/download/audio/2022/04/27/audio_4f3b1f3d9e.mp3?filename=afrobeat-instrumental-110624.mp3",art:"https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=500&q=85"}
];
const artists=[
 {name:"Luna Sol",type:"Dream pop · Chill",img:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=350&q=85"},
 {name:"Kofi Waves",type:"Afrobeats · Soul",img:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=350&q=85"},
 {name:"Nova Bloom",type:"Electronic · Indie",img:"https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=350&q=85"},
 {name:"Mira June",type:"Pop · R&B",img:"https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=350&q=85"}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const audio=$("#audio");
let currentTrack=null, playing=false, shuffle=false, repeat=false, activeGenre="All", libraryTab="liked", recent=[], toastTimer;
let liked=new Set(JSON.parse(localStorage.getItem("vibewave-liked")||"[]"));
const formatTime=s=>{if(!Number.isFinite(s))return"0:00";return`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`};
function notify(message){const t=$("#toast");t.textContent=message;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2200)}
function trackById(id){return tracks.find(t=>t.id===Number(id))}
function trackRow(t,i){return `<div class="track-row ${currentTrack?.id===t.id?"is-playing":""}" data-track-row="${t.id}"><div class="track-number">${currentTrack?.id===t.id&&playing?"♫":String(i+1).padStart(2,"0")}</div><div class="track-main"><img class="track-cover" src="${t.art}" alt="" loading="lazy"><div class="track-name"><strong>${t.title}</strong><span>${t.artist}</span></div></div><div class="track-album">${t.album}</div><div class="track-duration">${t.duration}</div><div class="track-actions"><button class="icon-button ${liked.has(t.id)?"liked":""}" data-like="${t.id}" aria-label="Like ${t.title}">${liked.has(t.id)?"♥":"♡"}</button><button class="row-play" data-play="${t.id}" aria-label="Play ${t.title}">${currentTrack?.id===t.id&&playing?"Ⅱ":"▶"}</button></div></div>`}
function renderTracks(selector,list){const el=$(selector);el.innerHTML=list.length?list.map(trackRow).join(""):`<div class="empty-state"><strong>Nothing here just yet</strong><p>Like a track or try another search to fill this space.</p></div>`}
function renderHome(){const moods=[["☾","Slow it down","Easy listening for quiet moments","chill"],["↗","Turn it up","Big energy, brighter days","energy"],["◉","Find your focus","Sounds for getting in the zone","focus"],["♫","Afro all day","Rhythm that moves with you","afro"]];$("#mood-grid").innerHTML=moods.map((m,i)=>`<button class="mood-card ${m[3]}" data-mood="${["Chill","Pop","Electronic","Afrobeats"][i]}"><span class="mood-icon">${m[0]}</span><strong>${m[1]}</strong><small>${m[2]}</small></button>`).join("");renderTracks("#trending-list",tracks.slice(0,5));$("#artist-grid").innerHTML=artists.map(a=>`<button class="artist-card" data-artist="${a.name}"><img src="${a.img}" alt="${a.name}" loading="lazy"><strong>${a.name}</strong><span>${a.type}</span></button>`).join("")}
function renderSearch(query=""){const q=query.toLowerCase().trim();const result=tracks.filter(t=>(activeGenre==="All"||t.genre===activeGenre)&&[t.title,t.artist,t.album,t.genre].some(v=>v.toLowerCase().includes(q)));$("#results-title").textContent=activeGenre==="All"?"All tracks":`${activeGenre} tracks`;$("#results-count").textContent=`${result.length} ${result.length===1?"track":"tracks"}`;renderTracks("#search-results",result)}
function renderGenres(){const genres=["All",...new Set(tracks.map(t=>t.genre))];$("#genre-pills").innerHTML=genres.map(g=>`<button class="genre-pill ${activeGenre===g?"active":""}" data-genre="${g}">${g}</button>`).join("")}
function renderLibrary(){const list=libraryTab==="liked"?tracks.filter(t=>liked.has(t.id)):recent.map(trackById).filter(Boolean);renderTracks("#library-list",list)}
function renderPlayer(){if(!currentTrack)return;$("#player-art").src=currentTrack.art;$("#player-title").textContent=currentTrack.title;$("#player-artist").textContent=currentTrack.artist;$("#player-like").textContent=liked.has(currentTrack.id)?"♥":"♡";$("#player-like").classList.toggle("liked",liked.has(currentTrack.id));$("#play-button").textContent=playing?"Ⅱ":"▶";$("#play-button").title=playing?"Pause":"Play";$$("[data-track-row]").forEach(row=>{const active=Number(row.dataset.trackRow)===currentTrack.id;row.classList.toggle("is-playing",active);const num=row.querySelector(".track-number");if(num)num.textContent=active&&playing?"♫":String([...row.parentElement.children].indexOf(row)+1).padStart(2,"0");const play=row.querySelector(".row-play");if(play)play.textContent=active&&playing?"Ⅱ":"▶"})}
function playTrack(track){if(!track)return;if(currentTrack?.id===track.id){togglePlayback();return}currentTrack=track;audio.src=track.src;audio.volume=Number($("#volume").value);recent=[track.id,...recent.filter(id=>id!==track.id)].slice(0,12);audio.play().then(()=>{playing=true;renderAll()}).catch(()=>{playing=false;renderAll();notify("Demo audio could not load. Try another track.")});renderPlayer()}
function togglePlayback(){if(!currentTrack){playTrack(tracks[0]);return}if(playing){audio.pause();playing=false;renderPlayer()}else{audio.play().then(()=>{playing=true;renderPlayer()}).catch(()=>notify("This audio sample could not be played."))}}
function nextTrack(direction=1){if(!currentTrack){playTrack(tracks[0]);return}let index=tracks.findIndex(t=>t.id===currentTrack.id);if(shuffle){let choices=tracks.filter(t=>t.id!==currentTrack.id);playTrack(choices[Math.floor(Math.random()*choices.length)]);return}index=(index+direction+tracks.length)%tracks.length;playTrack(tracks[index])}
function toggleLike(id){const n=Number(id);if(liked.has(n))liked.delete(n);else liked.add(n);localStorage.setItem("vibewave-liked",JSON.stringify([...liked]));renderAll();notify(liked.has(n)?"Added to Liked Songs":"Removed from Liked Songs")}
function showView(name){$$(".view").forEach(v=>v.classList.toggle("active",v.id===`${name}-view`));$$(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="search"){renderGenres();renderSearch($("#search-input").value)}if(name==="library")renderLibrary();$(".sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"})}
function renderAll(){renderPlayer();renderTracks("#trending-list",tracks.slice(0,5));renderSearch($("#search-input").value);renderLibrary()}
document.addEventListener("click",e=>{const play=e.target.closest("[data-play]");if(play){e.stopPropagation();const t=trackById(play.dataset.play);if(currentTrack?.id===t.id)togglePlayback();else playTrack(t);return}const like=e.target.closest("[data-like]");if(like){e.stopPropagation();toggleLike(like.dataset.like);return}const nav=e.target.closest("[data-view]");if(nav){showView(nav.dataset.view);return}const genre=e.target.closest("[data-genre]");if(genre){activeGenre=genre.dataset.genre;renderGenres();renderSearch($("#search-input").value);return}const mood=e.target.closest("[data-mood]");if(mood){activeGenre=mood.dataset.mood;showView("search");return}const artist=e.target.closest("[data-artist]");if(artist){$("#search-input").value=artist.dataset.artist;activeGenre="All";showView("search");renderSearch(artist.dataset.artist);return}const playlist=e.target.closest("[data-playlist]");if(playlist){if(playlist.dataset.playlist==="Liked Songs"){showView("library");libraryTab="liked";renderLibrary()}else{notify(`${playlist.dataset.playlist} playlist is a demo collection`)}return}});
$("#play-button").addEventListener("click",togglePlayback);$("#hero-play").addEventListener("click",()=>playTrack(tracks[0]));$("#hero-discover").addEventListener("click",()=>showView("search"));$("#explore-button").addEventListener("click",()=>showView("search"));$("#next-button").addEventListener("click",()=>nextTrack(1));$("#previous-button").addEventListener("click",()=>{if(audio.currentTime>3){audio.currentTime=0}else nextTrack(-1)});$("#shuffle-button").addEventListener("click",()=>{shuffle=!shuffle;$("#shuffle-button").classList.toggle("active",shuffle);notify(shuffle?"Shuffle is on":"Shuffle is off")});$("#repeat-button").addEventListener("click",()=>{repeat=!repeat;audio.loop=repeat;$("#repeat-button").classList.toggle("active",repeat);notify(repeat?"Repeat is on":"Repeat is off")});$("#player-like").addEventListener("click",()=>currentTrack&&toggleLike(currentTrack.id));$("#progress").addEventListener("input",e=>{if(Number.isFinite(audio.duration))audio.currentTime=audio.duration*Number(e.target.value)/100});audio.addEventListener("timeupdate",()=>{$("#current-time").textContent=formatTime(audio.currentTime);$("#total-time").textContent=formatTime(audio.duration);$("#progress").value=Number.isFinite(audio.duration)?audio.currentTime/audio.duration*100:0});audio.addEventListener("ended",()=>{if(!repeat)nextTrack(1)});audio.addEventListener("play",()=>{playing=true;renderPlayer()});audio.addEventListener("pause",()=>{playing=false;renderPlayer()});$("#volume").addEventListener("input",e=>audio.volume=Number(e.target.value));$("#search-input").addEventListener("input",()=>{activeGenre="All";renderGenres();renderSearch($("#search-input").value);if(!$("#search-view").classList.contains("active"))showView("search")});$$("[data-library]").forEach(b=>b.addEventListener("click",()=>{libraryTab=b.dataset.library;$$("[data-library]").forEach(x=>x.classList.toggle("active",x===b));renderLibrary()}));$("#add-playlist").addEventListener("click",()=>notify("Playlist creation is a future feature in this demo"));$("#premium-button").addEventListener("click",()=>notify("Vibe Plus is a demo button — no payment is taken"));$("#queue-button").addEventListener("click",()=>notify(`Up next: ${tracks[(tracks.findIndex(t=>t.id===currentTrack?.id)+1+tracks.length)%tracks.length].title}`));$("#mobile-menu").addEventListener("click",()=>$(".sidebar").classList.toggle("open"));$("#go-back").addEventListener("click",()=>notify("Use the menu to switch sections"));$("#go-forward").addEventListener("click",()=>showView("home"));document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search-input").focus()}if(e.code==="Space"&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName)){e.preventDefault();togglePlayback()}});
renderHome();renderGenres();renderSearch();renderLibrary();
